reagent-project/reagent-template

- project.clj
- src/leiningen/new/reagent.clj
- src/leiningen/new/reagent/project.clj
- src/leiningen/new/reagent/resources/templates/index.html
- src/leiningen/new/reagent/src/cljs/reagent/core.cljs
You might want to compare this to the changes you are planning to make.  There has been no comprehensive testing, but initial runs in a dev environment with figwheel have not completely collapsed.
Uses the new snapshot of weasel, the newish snapshot of piggieback, and the latest alpha of reagent.
Selmer templates have been stripped out of index.html.  I don't think they are required for dev and prod javascript, but I have also removed them for css.min.  If you decide to leave Selmer out, index.html could be moved up out of templates, I think.
> Update to accommodate clojurescript 0.0-2814, and corresponding changes in weasel

- src/leiningen/new/reagent/env/dev/clj/reagent/dev.clj
No reason to listen for connections from the outside.
> Listening on localhost instead of 0.0.0.0

- src/leiningen/new/reagent/env/dev/clj/reagent/dev.clj
piggieback/cljs-repl now accepts a repl-env as the first argument instead of as a keyword argument.
> Update dev.clj to conform to new piggieback api (issue #50)

- src/leiningen/new/reagent/.gitignore
Pretty sure you don't want that in your Git repository.
> Add figwheel_server.log to gitignore

- src/leiningen/new/reagent/env/dev/clj/reagent/repl.clj
With the current setup there's errors when you run lein repl because it tries to load this file that doesn't exist.
The clojurescript file only exists in the cljs flavour, not clj.
> There's no {{project-ns}}.dev

- src/leiningen/new/reagent.clj
Version 0.3.3 allows running tests with PhantomJS that access
localStorage
> Bump version of clojurescript.test 0.3.2 -> 0.3.3

- src/leiningen/new/reagent/project.clj
Based on history, it looks like the refactor-nrepl plugin should be included only with the +cider flag.
The plugin was originally added as part of ["add +cider flag"](https://github.com/reagent-project/reagent-template/commit/57bb972ff97bc63a19768c7d30605d2d11c4502d), but the template conditionals weren't formatted correctly, fixed in ["fixed typo"](https://github.com/reagent-project/reagent-template/commit/c26dcbd7f0f64270077b82ade84820b9b7d6b459).
> Include refactor-nrepl with the +cider flag

- README.md
`lein-cljsbuild` doesn't have `clean` subtask now, we just need to configure `:clean-targets` properly and use `lein clean`
> fix outdated readme

- README.md
- src/leiningen/new/reagent/project.clj
- src/leiningen/new/reagent/src/clj/reagent/handler.clj
- src/leiningen/new/reagent/src/cljs/reagent/core.cljs
This idiomatic change suggest to use [accountant](https://github.com/venantius/accountant) library for client-side rounting configuration.
The main idea is to use non-fragment hrefs and handle clicks via dom events.
If browser is capable enough and routes for href path is present, page will not cause reloading.
You may see an example at http://isomorph.clj.rocks . No matter, which browser you use - firefox, chrome or links. It will be routed correctly.
Changes summary:
- add server-side routes
- all href pointing to some-side client route will not cause page reload
- goog browser history api setup via accountant
- direct links to pages dispatched by client-side routes
> nearly isomorphic routing with accountant library

- src/leiningen/new/reagent/project.clj
Makes  new projects pass "lein check" and "lein ancient" without errors.
> Update to latest Figwheel and other dependencies. Make new projects pass lein check.

- src/leiningen/new/reagent/test/cljs/reagent/core_test.cljs
cause we use `cljs.test` here so should remove the nonexists macro `done` to prevent error like, the `done` macro is part of the deprecate project [clojurescript.test](https://github.com/cemerick/clojurescript.test)
```
Caused by: clojure.lang.ExceptionInfo: Referred macro cljs.test/done does not exist {:tag :cljs/analysis-error}
```
> remove nonexists macro

- src/leiningen/new/reagent/src/clj/reagent/handler.clj
`[:html]` is already implied in `html5`, so it can be removed.
`html5` also includes stuff like `<!DOCTYPE html>`, which are necessary to correctly render some Bootstrap stuff (and other css frameworks I would assume.)
> Use Hiccup's `html5' instead of `html'

- resources/leiningen/new/reagent/resources/public/css/site.css
- resources/leiningen/new/reagent/src/clj/reagent/handler.clj
The devcards CSS and the ``site.css`` site conflits for styling body element. I don't know if this minor fix is fine for the project, but works for me. So...
> avoiding conflits between devcards css and reagent site.css

- resources/leiningen/new/reagent/env/dev/clj/reagent/repl.clj
- resources/leiningen/new/reagent/project.clj
Enable start-figwheel! and cljs-repl from the repl namespace.
> Support for Figwheel and Piggieback from REPL

- resources/leiningen/new/reagent/env/dev/cljs/reagent/cards.cljs
Otherwise a lot of warnings is produced upon compilation (Use of undeclared Var).
> Fix missing dependency

- resources/leiningen/new/reagent/gitignore
- resources/leiningen/new/reagent/src/sass/site.scss
- src/leiningen/new/reagent.clj
- Adding a site.scss to illustrate the use of sass, and to be able to have live reloading of sass right from the start after running "lein sass watch" when a new project is created with the "+sass" option.
- Adding additional ignore entries to the `.gitignore` file, to ignore the output of the CSS resources and also to ignore the folder that is generated when building sass stylesheets that is used as a local cache.
> Sass enhancements

- resources/leiningen/new/reagent/project.clj
[VSCode Clojure plugin](https://marketplace.visualstudio.com/items?itemName=avli.clojure) can't starts in projects build-on reagent-template:
```bash
Error loading cemerick.piggieback: Could not locate cemerick/piggieback__init.class or cemerick/piggieback.clj on classpath.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by dynapath.defaults$eval31204$fn__31205 to method java.net.URLClassLoader.addURL(java.net.URL)
WARNING: Please consider reporting this to the maintainers of dynapath.defaults$eval31204$fn__31205
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.RuntimeException: …
```
> Add dependencies for cemerick.piggieback

- resources/leiningen/new/reagent/project.clj
See [this issue](https://github.com/BetterThanTomorrow/calva/issues/81)
> Update cider dependencies to please Calva requirements

- README.md
- resources/leiningen/new/reagent/project.clj
- resources/leiningen/new/reagent/src/cljs/reagent/core.cljs
- src/leiningen/new/reagent.clj
Clerks's scroll position management makes sense in many projects where the SPA should mimic a regular multipage site. But there are also cases where it might not be helpful. So that's why I am adding Clerk as an opt-out here.
Let me know if that does not make sense to you. 😄
> Add Clerk as an opt-out

- resources/leiningen/new/reagent/project.clj
- resources/leiningen/new/reagent/src/clj/reagent/handler.clj
This pr fix template devcards specific defaults when +devcards flag is used..
List of fixes :
* fix server side route for devcards
Currently localhost:3449/cards have no active mapping due to typo in routes definition, so devcards don't displayed at all. 
* add headers for devcards page
Without headers page don't interpreted as html and not displayed properly. For example in firefox it is just downloaded as text file
* bump devcards version to 0.2.6
When devcards are displayed they fail with React.createClass errors. Looks like this is some deprecation in React itself. Bumping devcards to the recent release fixes this.
> Devcards template part don't work at the moment.

- resources/leiningen/new/reagent/src/clj/reagent/handler.clj
Looks like default devcards route was removed in 4c31914c92803e2d1c42ce401abacc87d63a8c55 . This change is adding it back.
> add default devcards route

- resources/leiningen/new/reagent/resources/public/css/site.css
- resources/leiningen/new/reagent/src/cljs/reagent/core.cljs
There are 2 changes in this PR:
- link typo fix: /borken/link -> /**broken**/link
- site.css max-width changes to 640px. Original max-width is 600px, which breaks `reagent-tutorial` into 2 lines. Changing it to 640px makes it more user friendly.
> link typo fix: /borken/link -> /broken/link; site.css max-width changes to 640px

- resources/leiningen/new/reagent/src/clj/reagent/handler.clj
In JavaScript, `my-app` is not a valid variable name. It should be `my_app` under `window` object.
> Use `project-goog-module` inside script tag

- resources/leiningen/new/reagent/src/cljs/reagent/core.cljs
reagent.core/render was [deprecated](https://reagent-project.github.io/docs/master/reagent.core.html#var-render) in 0.10.0 in favor of reagent.dom/render.
> Fix reagent.core/render deprecated warning

- README.md
- resources/leiningen/new/reagent/README.md
- resources/leiningen/new/reagent/gitignore
- resources/leiningen/new/reagent/spec/cljs/reagent/core_spec.cljs
- resources/leiningen/new/reagent/test/cljs/reagent/core_test.cljs
Fixes Reagent warnings in tests generated by flags +test or +spec.
Also modified README suggesting chrome-headless instead of PhantomJS as a JS env to run doo.
Oh! Forgot to mention, the +spec tests are still broken.
> Fix Reagent deprecation warnings on tests

- resources/leiningen/new/reagent/env/dev/cljs/reagent/cards.cljs
Currently a fresh project with DevCards will throw a warning due to this deprecated function.
> Remove use of deprecated reagent.core/render

- resources/leiningen/new/reagent/README.md
The code block telling the user to run `lein figwheel devcards` to start the DevCards build is not generated correctly due to the wrong option name being used in README.md.
> fix faulty template data option name in README.md

- README.md
Heroku local has replaced foreman:
https://devcenter.heroku.com/changelog-items/692
(it is still possible to use foreman https://devcenter.heroku.com/articles/heroku-local#run-your-app-locally-using-foreman but not officially supported, so the documentation should probably suggest the supported approach?).
> Use heroku local instead of foreman

- resources/leiningen/new/reagent/shadow-cljs.edn
- resources/leiningen/new/reagent/src/clj/reagent/handler.clj
- resources/leiningen/new/reagent/src/cljs/reagent/core.cljs
Should use `:init-fn` instead of having html emit a function call. `:init-fn` ensures the function is called when the JS file is loaded and enables using `<script async>`. Didn't change that part but it is recommended.
Also removed the `:after-load` from the build config since it is recommended to use metadata hooks.
> Use recommend shadow-cljs setup for init/reload
